source 'https://github.com/CocoaPods/Specs.git'
#source 'https://github.com/kingiol/KDInteractiveNavigationController.git'

platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!

pod 'KDInteractiveNavigationController', :path => '../'